variable "commit_hash" {
  description = "Git commit hash, e.g. '1cdf2b5eb1a1f7967a9fa3587b1537823ddebaa5e'"
  type        = string
  default = ""
}

variable "project_id" {
  type = string
  default = "wiethecgi"
}

variable "region" {
  type    = string
  default = "europe-west3"
}

variable "zone" {
  type    = string
  default = "europe-west3-a"
}

variable tf_service_account {
  type = string
  default = "sa-wiethecgi-tf-dev@wiethecgi.iam.gserviceaccount.com"
}

variable "k8s_backend_service_name" {
  type        = string
  description = "Name of the backend service autogenerated by ingress-gce"
  default = "wiethecgi"
}

variable "k8s_master_allowed_ip" {
  type        = string
  description = "Kubernetes cluster master's external IP is only accessible from this IP"
  default = "0.0.0.0"
}

variable "domain" {
  type        = string
  description = "Domain name in form of example.com"
  default = "dev.wiethecgi.com"
}
